### ISSUE TITLE
Please add explicit LICENCE.txt at the top level

### ISSUE THREAD

**Issue by GadgetSteve** [willkessler/jupytergraffiti#13]
Getting approval to use Open Sourced tools, (even excellent ones), can be hard in many companies and involve the legal people - unfortunately expecting them to:

1. Read to the end of the user manual
2. Know, _or take the trouble to check,_ what the Jupyter Licence is

is a bit too much to ask. 

The convention of an explicit LICENCE.txt at the top level of the repository is a valuable one to follow - I think that GitHub actually parses it as well.

**Comment by willkessler** [comment]
Thank you for catching this oversight. It has been corrected. I am also working on updating user documentation this week for completeness/correctness. Any and all feedback appreciated!
