### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by deeplook** [willkessler/jupytergraffiti#40]
Any chance to make this pip (and/or conda)-installable?

**Comment by willkessler** [comment]
That's on the roadmap! How are you planning on using it? @deeplook

**Comment by willkessler** [comment]
hello @deeplook !

You can now install with `pip install jupytergraffiti` or `conda install -c willkessler jupytergraffiti`.

Please give it a try and let me know if it works for you. If it seems OK we will merge the branch that sets up for pip and conda builds.  Thanks a lot!

**Comment by willkessler** [comment]
Since pip installation and conda installation are now supported out of the box, I'm closing this ticket @deeplook . Thanks!
