### ISSUE TITLE
Separating out the terminal component

### ISSUE THREAD

**Issue by psychemedia** [willkessler/jupytergraffiti#41]
Is it possible to easily separate out the inline terminal into its own package?

I get the feeling it could be a handy thing to be able to drop into a non-graffiti notebook to provide an inline terminal. (It's possible to have a terminal and a notebook in view in JupyterLab, but to access a terminal when working in a traditional notebook requires opening the Jupyter terminal in another browser tab.)

Also, is there a way of resizing the inline terminal, eg making it draggable, or at least passing in a value that allows the height to be set manually?

**Comment by willkessler** [comment]
It is possible to separate out the inline terminal into its own package.  You would need to separate out the recording features of the terminals as Graffiti videos are hooked in to listen to their interactions in order to record all activities in them. `terminals.js` is what would need to become a standalone jupyter extension, and we've copied xterm.js into this repo to ensure its API and structures work with the Graffiti code.

Is this something you want to collaborate on @psychemedia?

You can currently control the height of the terminals by passing in a value. From the manual [here](https://github.com/willkessler/jupytergraffiti/blob/master/user_manual/UserManual.ipynb):

_You can control how many lines of text the shell has. Edit the metadata for the cell and change the "rows" entry to the number of desired rows:_
```
"graffitiConfig": {
    "rows": 6,
    "startingDirectory": "samples",
    "terminalId": "id_73csup4",
    "type": "terminal"
  }
```
_For instance, in the above metadata the current number of rows is 6. You could, for instance, change the number of rows to 12. In order for the change to "stick", you must save the Notebook and reload the page._

**Comment by psychemedia** [comment]
@willkessler Albeit having really dodgy Python skills, I'd be interesting in being able to use the terminal component and willing to have a stab at teasing what's necessary out of Jupyter graffiti.

At the moment, I'm just about to start looking at how to recast instructional material that scaffolds learning activities using IDLE to notebook based ones that embed the jupytergraffiti editor. That may turn up some additional considerations. (Hopefully this week, maybe next...)

**Comment by willkessler** [comment]
When you write 

> teasing what's necessary out of Jupyter graffiti

can you say more about what you meant? That is, could you use the terminal component as part of Jupyter Graffiti and just not the rest of the functionality, without extracting the terminal functionality in the code, but just using the extension as is? You don't have to make Graffiti videos or tips to use the terminals, you just click the terminal icon on the graffiti panel and it will insert terminals that will "just work" out of the box.

**Comment by psychemedia** [comment]
For the demo I need to do for myself, I just want to be able to embed one or more terminals in a notebook beneath particular code cells.

To reduce UI clutter, I don't want the Graffiti button in the toolbar (you wouldn't believe how hard the adoption path is trying to get others to accept new features in notebooks, so I have to hide as much as possible! Every new thing that appears in the toolbar button etc can just cause grief and argument...); for lightness / minimising risk of any errors (our distributions may have to last for years...) I want to reduce the weight/complexity of any extensions that are installed.

**Comment by willkessler** [comment]
Ok. But if there is no Graffiti button, what control would you use to
insert a terminal in the first place?

It could be added to Jupyter menus but that still changes the Jupyter
interface, if not immediately visible change.

When do you want to do your demo?

**Comment by psychemedia** [comment]
I was thinking I could hand craft s/thing into a cell, or provide a simple toolbar button for authors to insert the cell.

The demo is no a fixed point in time; putting it together is when I can find time to put it together....:-(

**Comment by willkessler** [comment]
So if there was a "terminal" toolbar button, (without the whole Graffiti
icon/label) then *that* would be ok? confused...

**Comment by psychemedia** [comment]
I want to turn a piece of teaching material that contains instructions like "Now go to IDLE and do so stuff" to some notebook based teaching material that contains instructions like "In the terminal below, do some stuff".

In the first case, I have to convince someone that the user experience is okay. If there is a Graffiti button, they'll complain, if there's a floating Graffiti control panel, they'll really complain. So I need to be able to give them a notebook with a clean end user experience containing embedded terminals at point of use, and nothing else, otherwise they'll get distracted about the something else and claim it wrecks the user experience and point out all sorts of things that they think are wrong with it..

I am the person in the first place producing the material, and if I have to hand craft the ipynb to force a clean terminal experience into the notebook, I will do. If there's an easier way, using the full Graffiti experience, whatever, that's fine.

(I already know that having to install a py package to run the terminal is going to cause grief, but I'll get round that using MyBinder in the short term.)

The cleanest end user experience I can think for someone not-me creating materials containing a terminal would be a toolbar button that inserts a terminal below the currently selected cell.

I know this all sounds daft but you wouldn't believe the extent to which folk will find excuses not to even try, let alone adopt, notebook practices. One of the classics is that markdown is too hard and unless there is a WYSIWYG editor, notebooks just won't work. When we provide WYSIWYG editors, they complain about the experience or the fact that an extension needs to downloaded, installed, enabled, configured etc etc.

**Comment by psychemedia** [comment]
Just by the by about rationale for the terminal: I also notice that folk are using notebooks for docs and devops, and having a handy inline terminal widget could be quite useful for those.

**Comment by willkessler** [comment]
So, something like this would be visible to all users (materials creators, and students). Would that be acceptable in your view?

![image](https://user-images.githubusercontent.com/176268/69201619-bba98080-0af3-11ea-8396-d7d9d63c9c58.png)

This button would insert a terminal below whatever cell is selected. You could edit the metadata of the terminal cell to set up an number of visible lines, and possibly an initial command to run.

**Comment by willkessler** [comment]
Alternatively, suppose you could set things up so that when the notebooks are distributed, the Graffiti panel button is not visible to end-users.... 

If that were possible, there would be no need to fork anything. Of course, you'd still have a heavier plugin than just terminals alone.

It seems to me like I should just add both options...

**Comment by willkessler** [comment]
BTW what is IDLE? link?

**Comment by psychemedia** [comment]
Yeah, that sort of thing could work well. With the whole plugin, I guess it would also allow for a notebook extensions configurator switch to enable the full Graffiti control panel?

Re: IDLE, it's a simple IDE that ships with python: https://docs.python.org/3/library/idle.html

**Comment by willkessler** [comment]
With the whole plugin, you'd turn off the graffiti control panel display with a notebook metadata value.

In the notebook metadata, there's a Graffiti section. I would add a parameter (true/false) to indicate whether you wanted the control panel button to be visible when the notebook is loaded. Before distributing the notebook, but after adding whatever Graffiti features you want e.g. terminals, you'd set this to false:

```
{
  "graffiti": {
    "dataDir": "../../../jupytergraffiti_data/",
    "firstAuthorId": "10467858656",
    "id": "id_ikelrdx",
    "language": "EN",
    "displayControlPanelButton": "false"
  },
...
}
```

You can edit notebook metadata from Jupyter's Edit menu.

How does that seem to you?

**Comment by psychemedia** [comment]
That looks like it could work.... Where would any toolbar button responsible for inserting a terminal be configured? Or would use case be:

- author uses full control panel to insert terminal
- author modifies notebook metadata to hide the Graffiti controls

**Comment by willkessler** [comment]
Your use case description would be exactly what I had in mind. We can get to that solution very rapidly, vs. creating a whole new (albeit smaller) terminals only plugin.

**Comment by willkessler** [comment]
To clarify: if the notebook metadata is modified to have `displayControlPanelButton:false`, then the full control button would not be shown. Otherwise, it would be shown.

If the author had hidden it and then wanted to see it again, they'd just edit the notebook metadata. Of course, a consumer of the notebook could do this too, although I don't know why they'd bother unless just curious.

The users will have to either have Graffiti installed, or visit the notebook somewhere where it is installed, in order to see the terminals.

**Comment by psychemedia** [comment]
@willkessler  That would work in first instance for me...

**Comment by willkessler** [comment]
Closing this since this has been addressed with https://github.com/willkessler/jupytergraffiti/pull/43
