### ISSUE TITLE
Terminal+code cell directory mappings on Mac

### ISSUE THREAD

**Issue by psychemedia** [willkessler/jupytergraffiti#42]
Hi

On a Mac (10.13.6), when using the terminal+code cell combination, the terminal's `pwd` is set to the directory in which the Jupyter server is running.

Clicking the `Jump to Notebook's Dir` link has no effect. For example, I can manually change directory in the terminal and run a `pwd` to check that I have changed directory (which works). Whatever directory I manually change to, clicking the `Jump to Notebook's Dir` link has no effect: the `pwd` returns the same thing before and after clicking the button.

A side effect of this is that clicking the `Run Code` button doesn't work in the general case - it will only work if the notebook (and hence the saved file) is in the same directory as the directory in which the notebook server was started.

**Comment by willkessler** [comment]
This is tricky because the way to detect what directory the notebook is located varies from system to system, but the jupyter server's directory is easily detected.

What would be desirable, `pwd` being the directory of the current notebook?

**Comment by psychemedia** [comment]
My issue was that the terminal+run button didn't work because the directory was set to the notebook server directory, not the notebook directory. (In "Jump to Notebook's Dir", what is the semantics of "Notebook" - the notebook, or the server?)

**Comment by willkessler** [comment]
I am working on a solution to this issue along with the other issue you brought to my attn (wanting to hide the Graffiti panel button). Fixes pending in a few days...

**Comment by psychemedia** [comment]
Thanks...I'd made a start on revising my own materials but had to put that on hold due to other commitments...

**Comment by willkessler** [comment]
OK PR in place... Just needs a little review. Probably merged by monday
https://github.com/willkessler/jupytergraffiti/pull/43

**Comment by willkessler** [comment]
@psychemedia  this PR is merged. Please test it out, the Jump to Notebooks' Dir function should work now, and you can control the display of the Graffiti Control panel button (turn it off) using notebook metadata. This is documented in the user_manual/UserManual.ipynb file at the bottom.

**Comment by willkessler** [comment]
Closing this issue since the request is satisfied.
