### ISSUE TITLE
Export video only html and javascript

### ISSUE THREAD

**Issue by zhc134** [willkessler/jupytergraffiti#44]
Hi,

Fantastic work! This extension really helps a lot when teaching code.
I wonder is there a way to export recorded video as raw html and javascript (without Jupyter's python kernel)

Thanks

**Comment by willkessler** [comment]
Do you mean as a video file e.g. mp4, or do you mean DOM manipulations of plain HTML not including the Jupyter system/server? (in either case, you would lose the interactivity of Graffiti videos in that you could no longer pause them to directly interact with Jupyter as it is displayed during the video).

**Comment by zhc134** [comment]
Thanks for your reply. I mean the latter (DOM manipulations as HTML and JS). 
Yes, I understand that I cannot interact with Jupyter kernel any more, but I just need the DOM manipulation, which might be much smaller than a video.

**Comment by willkessler** [comment]
Thanks for this info

What is your use case? I’d like to understand more about that. When regular
video is streamed (say off YouTube) it doesn’t take a ton of space locally
although obviously some minimal bandwidth is required. I think some minimal
bandwidth would be needed to stream pure DOM updates as well.

Why do your users not have access to Jupyter if you're teaching with it?

**Comment by zhc134** [comment]
Because I hope the students can view whole notebook as they want, jump to sections, view code, etc.  Also they can see instructions for each section or code snippet in their own pace.

**Comment by zhc134** [comment]
> Why do your users not have access to Jupyter if you're teaching with it?

Because we don't have enough computing resources... :(

**Comment by willkessler** [comment]
> Because I hope the students can view whole notebook as they want, jump to sections, view code, etc. Also they can see instructions for each section or code snippet in their own pace.

This is how Graffiti works now. It's an extension to regular notebooks so students can jump around, view code, while videos are playing or when they are not. For adding instructions to code snippets, you can add tooltips that are attached to specific keywords or phrases in the code to give students additional hints. 

This is demonstrated in the online examples that you can try on Binder, if it's not clear (see [this](https://mybinder.org/v2/gh/willkessler/jupytergraffiti/master?filepath=samples%2Fudacity%2Fc%2B%2B_nanodegree%2FFor%20Loops.ipynb) for an example)

**Comment by zhc134** [comment]
To make myself clear

> Because I hope the students can view whole notebook as they want, jump to sections, view code, etc. Also they can see instructions for each section or code snippet in their own pace.

is the response to 

> What is your use case? I’d like to understand more about that. When regular
> video is streamed (say off YouTube) it doesn’t take a ton of space locally
> although obviously some minimal bandwidth is required. I think some minimal
> bandwidth would be needed to stream pure DOM updates as well.

We think DOM updates has better experience than pure video. On the other hands, we don't have enough computing resources to run full Jupyter kernels. So I wonder if there is any approach to play the DOM updates in `jupytergraffiti_data` folder (without an actual python kernel running).

**Comment by willkessler** [comment]
So, you'd serve a jupyter notebook without a jupyter server serving the Jupyter notebook, or just, no kernel?  What actually renders the jupyter notebook if the jupyter server isn't running?

**Comment by willkessler** [comment]
Hello, take a look at this project:

https://www.rrweb.io/

It may serve your needs.
