### ISSUE TITLE
I can not install

### ISSUE THREAD

**Issue by gaoyi-byte** [willkessler/jupytergraffiti#58]
![image](https://user-images.githubusercontent.com/58095354/81278474-4ec97900-9088-11ea-81a0-a24d7f35c472.png)
![image](https://user-images.githubusercontent.com/58095354/81278513-5b4dd180-9088-11ea-86f8-2f5a0dda736d.png)

I have downloaded it, but there is no activation button。
I have reinstalled it several times and it won't work。
can you help me？

**Comment by willkessler** [comment]
Please see [this issue ](https://github.com/willkessler/jupytergraffiti/issues/57)which explains everything you need to know.

tldr; you can't run `pip install jupytergraffiti` from inside Jupyter as it is a server plugin (thus the Jupyter server itself needs to restart after installation via pip, not just the kernel). You can clone this repo and use `import jupytergraffiti` however, if you are unable to install a server plugin.

**Comment by willkessler** [comment]
Closing, reopen if you feel you can't solve it @gaoyi-byte
