### ISSUE TITLE
unable to save recording - lasts forever

### ISSUE THREAD

**Issue by yg42** [willkessler/jupytergraffiti#62]
Hello all !

I am trying to record a 6+ minutes codecast. It keeps displaying "Saving Graffiti Recordind. Please wait...", and nothing else happens.
I am working with Ubuntu 20.04.1 LTS, and graffiti 0.1.2 installed via pip (python 3.8). I tried on firefox (82.0) and chromium.

> jupyter core     : 4.6.3
> jupyter-notebook : 6.0.3
> qtconsole        : 4.7.4
> ipython          : 7.15.0
> ipykernel        : 5.3.0
> jupyter client   : 6.1.3
> jupyter lab      : not installed
> nbconvert        : 5.6.1
> ipywidgets       : 7.5.1
> nbformat         : 5.0.6
> traitlets        : 4.3.3

I am not sure how to debug or correct this problem, do you have any suggestion ?
The codecast contains images displayed with matplotlib, it makes use of numpy and skimage, but nothing computationnaly expensive. Thank you in advance.

**Comment by willkessler** [comment]
Are you able to create a shorter codecast, or never create any codecasts? That would help narrow down the problem.

**Comment by yg42** [comment]
yes, if the codecast is around 5 minutes, saving to disk takes a few minutes but terminates correctly and it can be played correctly as well.
If is takes a few seconds, everything is find and fast. I am sorry I cannot give a minimum working example. If you want, I can manage a visio-conf and show you how this happens.

**Comment by willkessler** [comment]
There might be a limit in Jupyter to cell size. Cells are used to persist the recording data (to get it from the UX to the kernel so it can write out the recording file).  You say it works up to 6 minutes long, and then has problems?

Is it possible, as a workaround, to make two recordings? You can attach recordings to any text in the notebook, so you could for instance attach them to text labelled "Part1" and "Part2"...

**Comment by yg42** [comment]
Yes, two recordings can be a workaround, I also shortened the speech, but sometimes one can want to have a "long" explanation.
I am sorry I do have the time nor the competences to debug this problem.

**Comment by willkessler** [comment]
Well I'll see what I can find out.

What are you using the tool for, out of curiosity?

**Comment by yg42** [comment]
We are constructing a MOOC on introduction to image processing and will use jupyter as a development environment, including graffiti for codecasts and nbgrader for automatic evaluation.

**Comment by willkessler** [comment]
@yg42 ,

I have just recorded a 6min, 7 second graffiti codecast with no issues, that plays back fine. I did it just using the binder link for the [general demo](https://mybinder.org/v2/gh/willkessler/jupytergraffiti/master?filepath=samples%2Fgeneral%2FGraffiti%20Basic%20Demo.ipynb), as shown on the README . 

I used the latest chrome for ubuntu.  

File is [here](https://s3.amazonaws.com/www.willkessler.com/long_rec.zip)

I will try an even longer recording now. Did you try just on the binder link above?

**Comment by willkessler** [comment]
@yg42  i just created a 10min+ recording with no issues. Granted, it took about 15s to close off the recording. However, binder did it just fine and I was able to play back the entire movie without any issues.  The recording took about 10mb to save, and therefore took about 5-6s to load over the network in order to play back the first time before browser caching kicked in.

**Comment by yg42** [comment]
Hello @willkessler . Sorry to bother again with this problem, I tried to record a ~3 min codecast, I again have a message "Saving Graffiti Recording. Please wait...".

I tried with chromium, firefox and opera under linux (ubuntu 22.04), same behavior. I am configured to use virtualenvs.

jupytergraffiti                   1.0.1.19
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.15.2
ipywidgets       : 8.0.2
jupyter_client   : 7.3.5
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.6
nbclient         : 0.6.3
nbconvert        : 7.0.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.2
traitlets        : 5.1.1

Do you have any idea on how to fix this ?

best regards
yann

**Comment by yg42** [comment]
@willkessler  I know why this is taking so long: I display and manipulate images in my notebook. If I record only sound with no image, this is really fast (less than a second), but with images, the saving time could be really long, more than a minute.

**Comment by willkessler** [comment]
hi @yg42 did you find a workaround? sorry for the lag, been extremely busy with my startup work.

**Comment by willkessler** [comment]
if not, when you say "manipulate images" do you mean, in the recording you're making you're moving images around? not sure i ever handled that case...

**Comment by yg42** [comment]
thanks @willkessler .
When I say "manipulate images", I mean displaying images via `plt.imshow`, after a few operations. I usually display 5-6 images et noticed that in this case, recording may take a long time.

Fortunately, after waiting for some time, it always ended correctly for each codecast I wanted to do.

**Comment by willkessler** [comment]
Interesting, do the images get produced by the recording when you play them
back? perhaps encoding them too is taking it far too long.

**Comment by yg42** [comment]
yes, they are produced and everything is fine when playing the recording.

What is also strange is that the size on disk does not move anymore after a very few seconds. But the message "please wait..." is still present. I should try to close the page and see if the recording can somehow be used in this state.

I'll keep you in touch.
