### ISSUE TITLE
Change directory for automatically created show/hide cells

### ISSUE THREAD

**Issue by 4flixt** [willkessler/jupytergraffiti#71]
The new feature to show/hide the currently selected cell creates a file with the cells content in the directory of the jupyter notebook. 
This can seriously clutter the main directory. It would be great if these files could either end up in the jupytergraffiti_data directory or any user defined directory.

**Comment by willkessler** [comment]
@4flixt I can see whether I can write these included files into the jupytergraffiti_data directory. Not sure it can be done due to security constraints... I'll investigate though.

**Comment by willkessler** [comment]
@4flixt 

I've reduced everything back to a single Show/Hide button control, which _by default_ creates an include file in the `graffiti_data` directory in a new subfolder called `includes` next to the recording data. It also deletes your source cell, leaving only the Show/Hide solution button in place.

You can now create Show/Hide buttons for either code or markdown cells, and it will preserve the cell type when you show the solution.

If you need to update a solution, simply show the solution, update the contents, create a new Show/Hide button from the updated cell, and get rid of your first Show/Hide button.

You can still modify the `%%insert_data_from_file`  directive, which now will use the keyword `implicit` for the file path, to use another file path, if you want to specify some solution file other than the one Graffiti generates from your source cell.

Please note that there is a small lag between the button showing up in Jupyter and when you can first click it; this only happens right after you create the button the first time, however. So if you click the button too soon, Graffiti may report that it can't find the include file. Just try again.

![ksnip_20210215-112150](https://user-images.githubusercontent.com/176268/107986054-2019f080-6f80-11eb-9b5a-8208deda59c2.png)

![Peek 2021-02-15 11-23](https://user-images.githubusercontent.com/176268/107986197-6707e600-6f80-11eb-9e8e-105f4d7d7e7f.gif)

Please note also that it's easy to record a movie that will play when the solution is shown. Just Show the solution, then record a movie associated with that button (it will say Rerecord in the Graffiti editor panel but it will also indicate that no movie has been recorded for this Graffiti yet).  This is nice when you want to explain more about the solution you're showing students. When a student clicks "Hide solution" the movie will automatically stop playing.

![ksnip_20210215-112610](https://user-images.githubusercontent.com/176268/107986361-bea65180-6f80-11eb-9095-82157bde9155.png)

Please try out these modifications and let me know if this satisfies your needs now.

**Comment by 4flixt** [comment]
Hi Will, this solution works perfectly for me, thank you! Makes our lives so much easier :)
