### ISSUE TITLE
Corrupted recordings

### ISSUE THREAD

**Issue by 4flixt** [willkessler/jupytergraffiti#73]
Occasionally it happens that a recording becomes corrupted and cannot be played back. The user is prompted to refer to the author of the notebook.
I cannot quite recreate the circumstances under which this happens. But even very short recordings in newly created notebooks with little content are sometimes affected. I estimate that this happens after every 10th recording on average.

The terminal in which the kernel is running displays such a message, whenever a corrupted recording is played:

```terminal
[W 12:14:19.864 NotebookApp] 404 GET /notebooks/Desktop/Untitled%20Folder/jupytergraffiti_data/notebooks/id_ly85cbk/authors/dev/cells/id_54j2cgx/graffitis/id_4ngbmrt/takes/id_wr1j07o/history.txt (::1) 1.620000ms referer=http://localhost:8888/notebooks/Desktop/Untitled%20Folder/Untitled.ipynb?kernel_name=python3
```

If this problem arises, no further uncorrupted recordings can be added to the notebook: Existing recordings are still available but new recordings will throw a similar error. 
To add further recordings the kernel needs to be restarted. 
While this solves the problem for new recordings, all presently corrupted recordings stay corrupted.

**Comment by willkessler** [comment]
@4flixt 

I've just tried to reproduce this. I created 11 markdown cells, and attached a new movie to each one. All recorded fine (granted, they were short), and the kernel didn't have an issue.

The 404 error msg above indicates that graffiti couldn't find the recording file stored on the system. If your kernel is python3, then I use `%%writefile` to persist graffiti data (magic command). This relies on the kernel working to actually write the data out to disk. If the kernel had crashed, then it makes sense that no data for the graffiti is being persisted and then can be later fetched for playback.

Early on during Graffiti's development, I used to crash my kernel by giving too much data on a single line to `%%writefile` . This might happen with extremely long recordings. To fix this problem, the long lines were chopped up and then recombined after fetching, so this should never happen today.  However, I wonder if there's possibly some memory constraint.  Have you tried to replicate the issue on another computer, and/or checked to see if Jupyter is using too much memory?

Also, you might try running graffiti in the included Docker container setup. That way you can be sure there's no other plugins or other Jupyter configurations that might be getting in Graffiti's way. Let me know if you need directions, the user manual explains the basics though.

**Comment by willkessler** [comment]
Just to add to this, you can do:

```sudo jupytergraffiti/build_and_run.sh```

to start docker/jupyter/graffiti on port `8888`, assuming you have docker set up and you're not already running jupyter on this port locally. (If you need to change the port just modify `build_and_run.sh`)

**Comment by zzc-ai** [comment]
The interface garbled，After I use import on Jetson, the interface appears garbled code, is it because Jetson is an ARM architecture instead of x86？thanks

**Comment by willkessler** [comment]
I'm not sure I know what you mean. Screen shot please?

**Comment by zzc-ai** [comment]
when i use arm computer to pip this file ,import will error ,but x86 will go. can it be work at arm computer?

**Comment by willkessler** [comment]
@4flixt can we close this ticket now?

**Comment by 4flixt** [comment]
Yes! I haven't encountered the problem in a while.  Thank you for looking into it!
