### ISSUE TITLE
[Firefox] Replaying recordings without sound after 3-4 seconds

### ISSUE THREAD

**Issue by 4flixt** [willkessler/jupytergraffiti#79]
This is a bit of weird issue that we have encountered on multiple machines using firefox:
Recording works fine and on playback everything seems to work at first. After 3-4 seconds the sound stops, however.
Movement of the cursor and other interactions continue playing until the end of the recording. 

Current workaround: Chrome works as expected.

**Comment by willkessler** [comment]
Can't repro using firefox and the existing recordings in the demo notebooks in this repo. At least, they play fine until the end. What version of FF?

**Comment by 4flixt** [comment]
hi Will, my college who had this issue can't reproduce it anymore. Sorry for wasting your time, I am closing this issue!
