### ISSUE TITLE
Graffiti does not work with jupyter notebook > 6.4.12

### ISSUE THREAD

**Issue by Mrfeli01** [willkessler/jupytergraffiti#91]
Hello, first of all thank you for providing this great tool. But there seems to be a problem with notebook > 6.4.12. Once a newer version of notebook is installed, the interactive text no longer works. We have now seen this problem with many of our students and the only way to solve it seems to be to reinstall notebook == 6.4.12.

If I open jupyter notebook with notebook == 6.5.0 installed I get the following console output
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: b8cfeda6-d1d5-48b2-8e9d-235c25888db0

Thank you
Felix

**Comment by Limmiche** [comment]
Hello @willkessler
I have the same issue and the only way to work around this problem is to install notebook == 6.4.12 or lower.

**Comment by willkessler** [comment]
Thanks for the heads up. I will look into this later this month and update here with what I find.

**Comment by willkessler** [comment]
@Limmiche @Mrfeli01 

I believe this is because newer versions of Jupyter Notebook have removed [lodash](https://lodash.com/), which used to be included and from which Graffiti uses several functions: `uniq`, `sortBy`, `debounce`, `clone`, `isEqual`, `contains`, and `union`.

Need to figure out how to get those functions re-included. Working on this...

**Comment by willkessler** [comment]
@Limmiche @Mrfeli01  I have corrected the issues in the latest pull request. I will get that merged as soon as it's approved but if you want to try it out you can install it via pip or conda, you should get `v1.0.1.20` of Graffiti to get the fixes.

**Comment by willkessler** [comment]
The fixes are merged. Let me know if you still see the issues. I did not see the error reported above, but I did see these other errors which I fixed, and I tested the tool in the latest Jupyter Notebook classic both locally and in docker.

**Comment by Mrfeli01** [comment]
Hey @willkessler, 
since I installed Graffiti v1.0.1.20, it works again with the latest version of Notebook without problems. Thank you for fixing the problem!

**Comment by willkessler** [comment]
Good news @Mrfeli01 !

I am curious as to how you use Graffiti so leave a note here if you care to share. Thanks!
